export const DOM = {
    'dashboard': '.dashboard',
    'dashboard-menu': '.dashboard__menu',
    'dashboard-menu-toggle': '.dashboard__menu--input',
    'dashboard-body': '.dashboard-body',
    'dashboard-cart': '.dashboard__sidebar--cart',
    'dashboard-cart-product': '.dashboard__sidebar--cart--product',
    'dashboard__cart-value': '.dashboard__sidebar--price--value',
    'dashboard__cart-number': '.dashboard__sidebar--header--cart',
    'product-popup-btn': '.product-detail__card--left--content--btn',
    'preloader' : '.preloader',
    'categories': '.food-capsule',
    'product' : '.product-detail',
    'product-name': '.product-detail__card--left--content--name',
    'product-price': '.product-detail__card--left--content--price',
    'product-moq': '.product-detail__card--left--content--moq',
    'product-img' : '.product-detail__card--right--img',
    'form': '.dashboard__form',
    'input': '.dashboard__input',
    'result': '.dashboard__input--results',
    'icon': '.dashboard__form--icon',
    'alert-box': '.alert',
    'alert-content' : '.alert__text',
    'favorites-list' : '.general__main--content--favorites--cards',
    'favorites' : '.general__main--content--favorites--card',
    'auth' : '.auth',
    'auth-popup': '.auth__popup',
    'auth-switch' : 'auth-toggle', //Passing the id not the class name
    'auth-label': '.auth__form--toggle',
    'auth-content' : '.auth__form',
    'auth-btn' : '.auth__form--btn',
    'current-user': '.dashboard__header--user',
    'sign-out' : 'sign-out', //ID for logout button,
    'general-nav' : '.general__sidebar__btns',
    'dashboard-nav': '.dashboard__menu__btns',
    'dashboard-mobile': '.dashboard__navbar--checkbox',
    'dashboard-tray' : '.dashboard__tray'
}