export const DOM = {
    'dashboard': '.dashboard',
    'dashboard-menu': '.dashboard__menu',
    'dashboard-menu-toggle': '.dashboard__menu--input',
    'dashboard-body': '.dashboard-body',
    'dashboard-cart': '.dashboard__sidebar--cart',
    'dashboard-cart-product': '.dashboard__sidebar--cart--product',
    'dashboard__cart-value': '.dashboard__sidebar--price--value',
    'dashboard__cart-number': '.dashboard__sidebar--header--cart',
    'product-popup-btn': '.product-detail__card--left--content--btn',
    'preloader' : '.preloader',
    'categories': '.food-capsule',
    'product' : '.product-detail',
    'product-name': '.product-detail__card--left--content--name',
    'product-price': '.product-detail__card--left--content--price',
    'product-moq': '.product-detail__card--left--content--moq',
    'product-img' : '.product-detail__card--right--img',
    'form': '.dashboard__form',
    'input': '.dashboard__input',
    'result': '.dashboard__input--results',
    'icon': '.dashboard__form--icon',
    'alert-box': '.alert',
    'alert-content' : '.alert__text',
    'favorites-list' : '.general__main--content--favorites--cards',
    'favorites' : '.general__main--content--favorites--card'
}